package backward;

import com.ftn.sbnz.model.models.RespiratorMode
import com.ftn.sbnz.model.models.ChangeRecord


query isModeAppropriate(
        String name,
        String group,
        Boolean patientConscious,
        Double deltaParticipationPercentage,
        Double deltaPO2,
        Double deltaPCO2
    )
    $rm: RespiratorMode(
        name,
        group,
        patientConscious;
    )
    // promenjen & -> || u 2. i 4. liniji evala
    eval(
        deltaParticipationPercentage > $rm.getParticipationPercentageLB() &&
        deltaParticipationPercentage < $rm.getParticipationPercentageUB() ||
        deltaPO2 > $rm.getpO2LB() && deltaPO2 < $rm.getpO2UB() ||
        deltaPCO2 > $rm.getpCO2LB() && deltaPCO2 < $rm.getpCO2UB()
    )
end

rule "Mode for patient"
    when
    then
end

rule "Recommended mode for patient"
    when
    then
end

rule "find mode"
    when
        RespiratorMode($sName:name, group == "Mode")
        RespiratorMode(this != $sName, group == $sName, $sSubmode:name)
    then
        System.out.println("UNIMPORTANT: " + $sSubmode + " is mode of " + $sName);
end

rule "find assisted mode"
    when
        isModeAppropriate(mode, type, false, 60.0, -7.0, 7.0;)
    then
        System.out.println(mode + " is " + type + " mode.");
end
