package rules.forward;
dialect  "mvel"

import com.ftn.sbnz.model.models.Patient
import com.ftn.sbnz.model.models.ChangeRecord

rule "intubate 1"
    when
        $p: Patient(respiratorMode == "APRV")
        ChangeRecord(patientId == $p.getId(), deltaPO2 < -2)
    then
        modify($p) {
            setConscious(false)
        }
end

rule "intubate 2"
    when
        $p: Patient(respiratorMode == "SIMV")
        ChangeRecord(patientId == $p.getId(), deltaPO2 < -2)
    then
        modify($p) {
            setConscious(false)
        }
end

rule "regain of consciussness 1"
when
        $p: Patient(respiratorMode == "APRV")
        ChangeRecord(patientId == $p.getId(), deltaPO2 > -2)
    then
        modify($p) {
            setConscious(true)
        }
end

rule "regain of consciussness 2"
    when
        $p: Patient(respiratorMode == "SIMV")
        ChangeRecord(patientId == $p.getId(), deltaPO2 > -2)
    then
        modify($p) {
            setConscious(true)
        }
end
