package rules.forward;
dialect  "mvel"

import com.ftn.sbnz.model.models.Patient
import com.ftn.sbnz.model.models.ChangeRecord

rule "intubate"
    when
        $p: Patient(respiratorMode == "APRV", FiO2 >= 75)
        ChangeRecord(patientId == $p.getId(), deltaPO2 < 0)
    then
        modify($p){
            setConscious(false)
        }
end

rule "regain of consciussness"
    when
        $p: Patient(respiratorMode == "SIMV", FiO2 <= 25 )
        ChangeRecord(patientId == $p.getId(), deltaPO2 > 0)
    then
        modify($p){
            setConscious(true)
        }
end
