import com.ftn.sbnz.model.models.Patient
import com.ftn.sbnz.model.models.RespiratorDecision

rule "Frequency decision"
    when
        Patient($id: id, frequency > 35)
        $decision: RespiratorDecision(patientId == $id, frequencyDecision == false)
    then
        modify($decision){setFrequencyDecision(true)};
        System.out.println("Frequency: true");
end

rule "Tidal volumen decision"
    when
        Patient($id: id, tidalVolume < 5 * weight)
        $decision: RespiratorDecision(
            patientId == $id,
            frequencyDecision == true,
            tidalVolumeDecision == false
        )
    then
        modify($decision){setTidalVolumeDecision(true)};
        System.out.println("tidalVolume: true");
end

rule "pCO2 decision"
    when
        Patient($id: id, pCO2 > 7)
        $decision: RespiratorDecision(
            patientId == $id,
            frequencyDecision == true,
            tidalVolumeDecision == true,
            pCO2Decision == false
        )
    then
        modify($decision){setPCO2Decision(true)};
        System.out.println("pCO2: true");
end

rule "pO2 decision"
    when
        Patient($id: id, pO2 < 8)
        $decision: RespiratorDecision(
            patientId == $id,
            frequencyDecision == true,
            tidalVolumeDecision == true,
            pCO2Decision == true,
            pO2Decision == false
        )
    then
        modify($decision){setPO2Decision(true)};
        System.out.println("pO2: true");
end

rule "Final decision"
    when
        Patient($id: id, $name: name)
        $decision: RespiratorDecision(
            patientId == $id,
            frequencyDecision == true,
            tidalVolumeDecision == true,
            pCO2Decision == true,
            pO2Decision == true
        )
    then
        $decision.setFinalDecision(true);
        System.out.println("Patient " + $name + " must be put on the respirator!");
end

