//package cep;
//
//import com.ftn.sbnz.model.events.ChangeEvent
//import com.ftn.sbnz.model.events.PO2Change
//import com.ftn.sbnz.model.models.Patient
//import com.ftn.sbnz.model.models.ChangeRecord
//
//rule "change event"
//    no-loop
//    when
//        $patient: Patient($id: id, respiratorMode == "CPAP" || respiratorMode == "APRV" , FiO2 < 75)
//        $record: ChangeRecord(patientId == $id)
//        $change: ChangeEvent(
//            $id == patientId, // ovde templejti
//            deltaPO2 <= -1.5 ||
//            deltaPCO2 >= 0.5 ||
//            deltaParticipationPercentage >= 25
//        )
//    then
//        modify($patient) {
//            setFiO2($patient.getFiO2() + 25),
//            setpO2($patient.getpO2() + $change.getDeltaPO2()),
//            setpCO2($patient.getpCO2() + $change.getDeltaPCO2()),
//            setParticipationPercentage($patient.getParticipationPercentage() - $change.getDeltaParticipationPercentage())
//        };
//        modify($record){
//            setDeltaPO2($record.getDeltaPO2() + $change.getDeltaPO2()),
//            setDeltaPCO2($record.getDeltaPCO2() + $change.getDeltaPCO2()),
//            setParticipationPercentage($patient.getParticipationPercentage())
//        };
//        delete($change);
//        System.out.println("Patient FiO2 increased: " + $patient.getFiO2());
//end
//
//rule "change event cap"
//    no-loop
//    when
//        $patient: Patient($id: id, respiratorMode == "CPAP" || respiratorMode == "APRV" , FiO2 >= 75)
//        $record: ChangeRecord(patientId == $id)
//        $change: ChangeEvent(
//            $id == patientId, // ovde templejti
//            deltaPO2 <= -1.5 ||
//            deltaPCO2 >= 0.5 ||
//            deltaParticipationPercentage >= 25
//        )
//    then
//        modify($patient) {
//            setpO2($patient.getpO2() + $change.getDeltaPO2()),
//            setpCO2($patient.getpCO2() + $change.getDeltaPCO2()),
//            setParticipationPercentage($patient.getParticipationPercentage() - $change.getDeltaParticipationPercentage())
//        };
//         modify($record){
//            setDeltaPO2($record.getDeltaPO2() + $change.getDeltaPO2()),
//            setDeltaPCO2($record.getDeltaPCO2() + $change.getDeltaPCO2()),
//            setParticipationPercentage($patient.getParticipationPercentage())
//        };
//        delete($change);
//        System.out.println("Patient FiO2 reached 75%. Consider changing the mode.");
//end
