package cep;

import com.ftn.sbnz.model.events.ChangeEvent
import com.ftn.sbnz.model.events.PO2Change
import com.ftn.sbnz.model.models.Patient
import com.ftn.sbnz.model.models.ChangeRecord

rule "change event control variable 1"
    no-loop
    when
        $patient: Patient($id: id, respiratorMode == "SIMV" || respiratorMode == "KMV/AC", volumeControlled == true)
        $record: ChangeRecord(patientId == $id)
        $change: ChangeEvent(
            $id == patientId, // ovde templejti
            deltaPO2 <= -1.5 ||
            deltaPCO2 >= 0.5 ||
            deltaParticipationPercentage >= 25
        )
    then
        modify($patient) {
            setVolumeControlled(false),
            setpO2($patient.getpO2() + $change.getDeltaPO2()),
            setpCO2($patient.getpCO2() + $change.getDeltaPCO2()),
            setParticipationPercentage($patient.getParticipationPercentage() - $change.getDeltaParticipationPercentage())
        };
        modify($record){
            setDeltaPO2($record.getDeltaPO2() + $change.getDeltaPO2()),
            setDeltaPCO2($record.getDeltaPCO2() + $change.getDeltaPCO2()),
            setParticipationPercentage($patient.getParticipationPercentage())
        };
        delete($change);
        System.out.println("Control variable changed.");
end

rule "change event control variable level 2"
    no-loop
    when
        $patient: Patient($id: id, respiratorMode == "SIMV" || respiratorMode == "KMV/AC", volumeControlled == false)
    then
        modify($patient) {
            setPressure(2.5)
        };
        System.out.println("Pressure changed.");
end

rule "change event control variable level 3"
    no-loop
    when
        $patient: Patient(
            $id: id, respiratorMode == "SIMV" || respiratorMode == "KMV/AC",
            volumeControlled == false,
            pressure == 2.5
        )
    then
        modify($patient) {
            setTidalVolume(
                ($patient.getCompliance() * $patient.getPressure() -
                $patient.getCompliance() * $patient.getGasFlow() * $patient.getResistance()) * 100
            ),
            setFrequency((int) ($patient.getMinuteVolume() / $patient.getTidalVolume()))
        };
        System.out.println("Tidal volume:" + $patient.getTidalVolume() + " freq: " + $patient.getFrequency());
end

rule "change FiO2"
    no-loop
    when
        $patient: Patient(
            $id: id, respiratorMode == "SIMV" || respiratorMode == "KMV/AC",
            FiO2 < 75,
            volumeControlled == false
        )
        $record: ChangeRecord(patientId == $id)
        $change: ChangeEvent(
            $id == patientId, // ovde templejti
            deltaPO2 <= -1.5 ||
            deltaPCO2 >= 0.5 ||
            deltaParticipationPercentage >= 25
        )
    then
        modify($patient) {
            setFiO2($patient.getFiO2() + 25),
            setpO2($patient.getpO2() + $change.getDeltaPO2()),
            setpCO2($patient.getpCO2() + $change.getDeltaPCO2()),
            setParticipationPercentage($patient.getParticipationPercentage() - $change.getDeltaParticipationPercentage())
        };
        modify($record){
            setDeltaPO2($record.getDeltaPO2() + $change.getDeltaPO2()),
            setDeltaPCO2($record.getDeltaPCO2() + $change.getDeltaPCO2()),
            setParticipationPercentage($patient.getParticipationPercentage())
        };
        delete($change);
        System.out.println("Patient FiO2 increased: " + $patient.getFiO2());
end


rule "change FiO2 cap"
    when
        $patient: Patient(
            $id: id, respiratorMode == "SIMV" || respiratorMode == "KMV/AC",
            FiO2 >= 75,
            volumeControlled == false
        )
        $record: ChangeRecord(patientId == $id)
        $change: ChangeEvent(
            $id == patientId, // ovde templejti
            deltaPO2 <= -1.5 ||
            deltaPCO2 >= 0.5 ||
            deltaParticipationPercentage >= 25
        )
    then
        modify($patient) {
            setpO2($patient.getpO2() + $change.getDeltaPO2()),
            setpCO2($patient.getpCO2() + $change.getDeltaPCO2()),
            setParticipationPercentage($patient.getParticipationPercentage() - $change.getDeltaParticipationPercentage())
        };
         modify($record){
            setDeltaPO2($record.getDeltaPO2() + $change.getDeltaPO2()),
            setDeltaPCO2($record.getDeltaPCO2() + $change.getDeltaPCO2()),
            setParticipationPercentage($patient.getParticipationPercentage())
        };
        delete($change);
        System.out.println("Patient FiO2 reached 75%. Consider changing the mode.");
end