package cep;

import com.ftn.sbnz.model.events.ChangeEvent
import com.ftn.sbnz.model.events.PO2Change
import com.ftn.sbnz.model.events.InhaleEvent
import com.ftn.sbnz.model.models.Patient
import com.ftn.sbnz.model.models.ChangeRecord
import com.ftn.sbnz.model.events.InhaleEvent


rule "inhale event control variable level 1"
    no-loop
    when
        $patient: Patient($id: id, respiratorMode == "SIMV" || respiratorMode == "KMV/AC", volumeControlled == true)
        Number(doubleValue < $patient.getMinuteVolume()) from accumulate(
            $ie: InhaleEvent(patientId == $id)
            over window: time(1m), sum($ie.getInhaledVolume())
        )
    then
        modify($patient) {
            setVolumeControlled(false)
        };
        System.out.println("Control variable changed.");
end

rule "inhale event FiO2"
    no-loop
    when
        $patient: Patient(
            $id: id, respiratorMode == "SIMV" || respiratorMode == "KMV/AC",
            FiO2 < 75,
            volumeControlled == false
        )
        Number(doubleValue < $patient.getMinuteVolume()) from accumulate(
            $ie: InhaleEvent(patientId == $id)
            over window: time(1m), sum($ie.getInhaledVolume())
        )
    then
        modify($patient){setFiO2($patient.getFiO2() + 25)};
        System.out.println("Patient FiO2 increased: " + $patient.getFiO2());
end

rule "inhale event FiO2 cap"
    no-loop
    when
        $patient: Patient(
            $id: id, respiratorMode == "SIMV" || respiratorMode == "KMV/AC",
            FiO2 >= 75,
            volumeControlled == false
        )
        Number(doubleValue < $patient.getMinuteVolume()) from accumulate(
            $ie: InhaleEvent(patientId == $id)
            over window: time(1m), sum($ie.getInhaledVolume())
        )
    then
         System.out.println("Patient FiO2 reached 75%.");
end
